### ISSUE TITLE
Regarding the problem of displaying multiple point clouds at the same time？

### ISSUE THREAD

**Issue by jiangchaokang** [hasancaslan/PointFlowRenderer3#2]
Excellent work, but I have a little question. Please tell me what should I do if I want to display multiple point clouds at the same time in a scene?

**Comment by hasancaslan** [comment]
Thank you for the kind words. First idea comes to my mind is combining multiple point clouds into one. 

Or you can merge XML files into one and then render in the same scene as follows:

1. Load all your point cloud data sets.
2. Standardize and preprocess each set just like we do for a single set.
3. While generating the XML content, iterate over all the preprocessed point cloud sets, appending their XML ball segments to the xml_segments list.

This way, the final XML file will describe a scene with all your point clouds, and when you render it, all of them will appear together.
